name: batch
description: A lightweight and powerful Job Scheduling Framework written in Dart. With this framework, you can easily develop a job scheduling and batch program in Dart.
version: 0.6.0
homepage: https://github.com/batch-dart/batch.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  clock: ^1.1.0
  console_color: ^1.0.0
  http: ^0.13.4
  json_response: ^2.3.2
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
  import_sorter: ^4.6.0
  dart_code_metrics: ^4.13.0
  mock_web_server: ^5.0.0-nullsafety.1
