name: batch
description: A Lightweight and Powerful Job Scheduling Framework written in Dart. With this framework, you can easily develop a job scheduling and batch program in Dart.
version: 1.1.0
homepage: https://github.com/batch-dart/batch.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  console_color: ^1.0.0
  http: ^0.13.4
  args: ^2.3.0
  async_task: ^1.0.18
  intl: ^0.17.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0
  import_sorter: ^4.6.0
  dart_code_metrics: ^4.14.0
  mock_web_server: ^5.0.0-nullsafety.1
